export enum Operator {
    Equals = "==",
    NotEquals = "!=",
    GreaterThan = ">",
    LessThanOrEqual = "<=",
    LessThan = "<",
    GreaterThanOrEqual = ">",
    Between = "between",
    NotBetween = "not between",
    In = "in",
    NotIn = "not in",
    StartsWith = "starts",
    NotStartsWith = "not starts",
    EndsWith = "ends",
    NotEndsWith = "not ends",
    Contains = "contains",
    NotContains = "not contains",
}